server:
  port: 8761

spring:
  application:
    name: discoveryservice


eureka:
  server:
    initial-capacity-of-response-cache: 3000
  client:
    register-with-eureka: false
    fetch-registry: false
